# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a75tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/abhishek/Verilog/Processor/Processor.cache/wt [current_project]
set_property parent.project_path /home/abhishek/Verilog/Processor/Processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/RegisterFile.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/PC.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/JumpLogic.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/IMEM.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/DMEM.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/decode.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/BranchLogic.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/ALU.v
  /home/abhishek/Verilog/Processor/Processor.srcs/sources_1/new/RV32I_CPU.v
}
synth_design -top RV32I_CPU -part xc7a75tcsg324-1
write_checkpoint -noxdef RV32I_CPU.dcp
catch { report_utilization -file RV32I_CPU_utilization_synth.rpt -pb RV32I_CPU_utilization_synth.pb }
